# Generated by Django 3.2.5 on 2021-08-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pic/', verbose_name='Profile Picture'),
        ),
    ]
