# Generated by Django 3.2.5 on 2021-08-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_userprofile_image'),
        ('Article', '0003_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='readers',
        ),
        migrations.AddField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='_Article_article_readers_+', related_query_name='readed_users', to='Profile.UserProfile'),
        ),
    ]
