# Generated by Django 3.2.5 on 2021-08-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_userprofile_image'),
        ('Article', '0005_auto_20210814_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reader',
            field=models.ManyToManyField(blank=True, related_name='readed', related_query_name='readed_users', to='Profile.UserProfile'),
        ),
    ]
